pub_rate: 2.0
analyzers:
    sensors:
      type: diagnostic_aggregator/StatusAnalyzer
      path: Sensors
      analyzers:
        ims_leaks:    
            type: diagnostic_aggregator/GenericAnalyzer
            path: Leaks
            contains: Leaks
        ims_pressure:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Pressure
            contains: Pressure
        ims_temp:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Temperature
            contains: Temperature
        imu:
            type: diagnostic_aggregator/GenericAnalyzer
            path: IMU
            contains: IMU  