# ROS node rate 
# ROS Topics
topics:
  subscribers:
    yaw: "/ref/yaw"
    pitch: "/ref/pitch"
    roll: "/ref/roll"
    yaw_rate: "/ref/yaw_rate"
    pich_rate: "/ref/pitch_rate"
    roll_rate: "ref/roll_rate"
    surge: "/ref/surge"
    sway: "/ref/sway"
    heave: "/ref/heave"
    depth: "/ref/depth"
    altitude_ref: "/ref/altitude"
    state: "/nav_filter/state"
  publishers:
    thrust_body_request: "thrust_body_request"
    thrusters: "/thrusters/rpm_command"


