# topics:
#     publishers:
#         medusa_fix: publishes usbl fixes of comapitible with medusa software
#     subscribers:
#         dmac_fix: receives third party usbl fixes, here - evologics-dmac 

topics:
    publishers:
        medusa_fix: "measurement/usbl_fix"
    subscribers:
        dmac_fix: "modem/measurement/usbl_fix"