# ROS node rate 
period: 0.2

allocation_matrix: [ 0.707, -0.707, 0.0, -0.2, -0.2, 0.0,  ## medusa thrusters.
                     0.707,  0.707, 0.0, -0.2,  0.2, 0.0,  # First 3 elements in each row represent unit allocation vector i.e. contribution of the thruster force in 3d space
                     0.707, -0.707, 0.0,  0.2,  0.2, 0.0,  # Last  3 elements in each row represent position of the thruster wrt the COM
                     0.707,  0.707, 0.0,  0.2, -0.2, 0.0]  # Size of the allocation matrix is nx6, where n = no of thrusters 
                  #  0.0,    0.0,   1.0,  0.0, -0.1, 0.0,  # Last  3 elements in each row represent position of the thruster wrt the COM
                  #  0.0,    0.0,   1.0,  0.0,  0.1, 0.0]  # Size of the allocation matrix is nx6, where n = no of thrusters 

#Forces (N) = ct[0]*RPM^2 + c[1]*RPM + c[2]
ctf: [0.00000177778, 0.0, 0.0]     # parameters for medusa seabotix, eqn -> Thrust = f(rpm)
ctb: [-0.00000177778, 0.0, 0.0]     # parameters for medusa seabotix, eqn -> Thrust = f(rpm)

#Maximum thrust each thruster is capable of outputting (N)
max_thrust_norm: 36.0
min_thrust_norm: -36.0

# RPM max value /100
actuators_gain: [45.0, 45.0, 45.0, 45.0]            # Inputs to actuators will be scaled to actuators_gain

# Yaw Params
yaw/kp: 0.3
yaw/ki: 0.001
yaw/kd: 0.02
yaw/max_error: 60.0 # deg
yaw/min_error: -60.0 # deg  
yaw/max_out: 14.0 # N.m
yaw/min_out: -14.0

# Yaw Rate Params
yaw_rate/kp: 0.16
yaw_rate/ki: 0.04444
yaw_rate/max_error: 3.0 # deg
yaw_rate/min_error: -3.0 # deg  
yaw_rate/max_out: 14.0 # N.m
yaw_rate/min_out: -14.0

# Pitch Params  
pitch/kp: 5.0
pitch/ki: 0.0001
pitch/kd: 5.0
pitch/max_error: 45.0 # deg
pitch/min_error: -45.0 # deg  
pitch/max_out: 38.0 # N.m
pitch/min_out: -38.0

# Surge Params
surge/kp: 6
surge/ki: 1 
surge/max_ref_value: 0.7  # m/s
surge/min_ref_value: -0.7 # m/s
surge/max_error: 0.2 # m/s
surge/min_error: -0.2 # m/s  
surge/max_out: 60.0 # N
surge/min_out: -60.0

# Sway Params
sway/kp: 180
sway/ki: 20 
sway/max_ref_value: 0.7  # m/s
sway/min_ref_value: -0.7 # m/s
sway/max_error: 0.2 # m/s
sway/min_error: -0.2 # m/s  
sway/max_out: 60.0 # N
sway/min_out: -60.0


# Depth Params
depth/kp: 15
depth/ki: 0.7
depth/kd: 20.0
depth/max_error: 3.0 # m
depth/min_error: -3.0 # m  
depth/max_out: 50.0 # N
depth/min_out: -50.0

# Altitude Params
altitude/kp: 10.0
altitude/ki: 0.3
altitude/kd: 30.0
altitude/max_error: 3.0 # m
altitude/min_error: -3.0 # m  
altitude/max_out: 50.0 # N
altitude/min_out: -50

